# Generated by Django 5.1.5 on 2025-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercedatabase',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ecommercedatabase',
            name='number',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='ecommercedatabase',
            name='password',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
