# Generated by Django 5.1.5 on 2025-02-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_ecommercedatabase_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommercedatabase',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
