# Generated by Django 5.1.5 on 2025-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantDatabase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mname', models.CharField(max_length=255)),
                ('mnumber', models.CharField(max_length=50, unique=True)),
                ('memail', models.EmailField(max_length=255, unique=True)),
            ],
        ),
    ]
