# Generated by Django 5.1.5 on 2025-02-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantdatabase',
            name='memail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
